import { existsSync } from "node:fs";
import { loadEnvFile } from "node:process";
for (const f of [".env.local", ".env"]) if (existsSync(f)) loadEnvFile(f);
const { prisma } = await import("../data/client.ts");
const toplam = await prisma.specFieldSource.count();
const kaynak = await prisma.specFieldSource.groupBy({ by: ["source"], _count: true });
console.log("toplam alan damgasi:", toplam);
for (const k of kaynak) console.log(" ", k.source, k._count);
const ornek = await prisma.specFieldSource.findMany({ where: { part_id: "nvidia-rtx-4090" }, select: { field_name: true, source: true, confidence: true } });
console.log("\nnvidia-rtx-4090:", ornek.map(o => `${o.field_name}=${o.source}`).join(", "));
await prisma.$disconnect();
